public enum SemanticErrors{
	DTYPE_MISMATCH,
	CONSTANT_REASSIGNMENT,
	MULTIPLE_VAR_DECLARATION,
	UNDECLARED_VAR,
	UNDECLARED_FUNC,
	MULTIPLE_FUNC_DECLARATION,
	PARAMETER_MISMATCH,
	EXPECTING_RETURN,
	UNEXPECTING_RETURN
}
	